#!/usr/bin/env python3

# Tasmota Lightning Control (tlc)
# (c) 2020 Ddw (GPL when released)

import time
import sys
import requests
import argparse
import configuration as cfg 
import webcall as web

def main():
  
    if args.state == 'on':

        if args.rise == 'fast':
            lights_rise("fast", args.dim)

        elif args.rise == 'slow':
            lights_rise("slow", args.dim)

        elif args.col:
            setcol(args.col, args.dim)

        elif args.ct:
            setct(args.ct, args.dim)

        else:
            lights_on(args.dim)
    else:
        lights_off()


    sys.exit() 


def lights_on(dim_value):
    for _ in spot_list:
        print("Turn on", _)
        r = requests.get(web.call("method") + _ + web.call("spot_on"))
        r = requests.get(web.call("method") +  _ + web.call("dimmer") + str(dim_value))
    return        

def lights_off():
    for _ in spot_list:
        print("off", _)
        r  = requests.get(web.call("method") + _ + web.call("spot_off"))
    return

def lights_rise(speed, dim_max):
    if speed == 'slow':
        n = 1
    else:
        n = 5

    print("dimmer up", n)
    for _ in spot_list:
        for dim_value in range(0, dim_max+10, n):
            r = requests.get('http://' +  _ + web.call("dimmer") + str(dim_value))

def setcol(color_value, dim_value):
    print("set color")
    for _ in spot_list:
            r = requests.get(web.call("method") +  _ + web.call("color") + str(color_value))
            r = requests.get(web.call("method") +  _ + web.call("dimmer") + str(dim_value))

def setct(ct_value, dim_value):
    print("Set color temperature")
    for _ in spot_list:
            r = requests.get(web.call("method") +  _ + web.call("color_temp") + str(ct_value))
            r = requests.get(web.call("method") +  _ + web.call("dimmer") + str(dim_value))

def set_fade(fade_value):
    if fade_value == 'on':
      for _ in spot_list:
            r = requests.get(web.call("method") +  _ + web.call("fade_on"))
            print(r)
    elif fade_value == 'off':
      for _ in spot_list:
            r = requests.get(web.call("method") +  _ + web.call("fade_off"))
            print(r)
    else:
            print('No on or off specified.')

    sys.exit()


def getgroups():

    print('Available device groups: ')

    groups = cfg.get_groups()

    for c, _ in enumerate(groups):
      print(str(c+1) + ": ", _)
    
    sys.exit()

def process_args():

    # Parse arguments and set sane defaults if any parameters are missing.

    global args
    global spot_list

    parser=argparse.ArgumentParser(description='lsc_ctrl - controlling LSC bulbs')

    parser.add_argument('--group', type = str, help="Specify which group you want control!")
    parser.add_argument('--state', type = str, help="'on' and 'off' are supported.")
    parser.add_argument('--rgb', type = str, help="Add start RGB value")
    parser.add_argument('--dim', type = str, help="Add dim value")
    parser.add_argument('--rise', type = str, help="Slowly turn on lights")
    parser.add_argument('--col', type = str, help="Set color 0-15")
    parser.add_argument('--ct', type = str, help="Set color temperature 153-500.")
    parser.add_argument('--fade', type = str, help="Turn fading 'on' or 'off'.")
    parser.add_argument('--getgroups', help="Show available groups", action="store_true")

    if len(sys.argv) == 1:
      parser.print_help(sys.stderr)
      sys.exit(1)

    args=parser.parse_args()

    spot_list = cfg.get_group_ipaddr(args.group)

    if args.getgroups:
      getgroups()

    if args.fade:
      set_fade(args.fade)

    if not args.group:
      print ('You must specify a group using: --group')
      sys.exit()

    if not spot_list:
      print('No spots found in group: ' + args.group + '. Dit you specify to correct group?')
      print()
      print('Pro tips:')
      print()
      print(' - use --getgroups to view available groups')
      print(' - edit devices.yaml to define your devices and groups!')
    
      sys.exit(1)


process_args()
main()

